### PR TITLE
bump ziti-tunnel version

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
This is the kind of change to our Helm chart(s) for which we'll need to coordinate systematic updates of all the consumers. For example, Rancher partner charts repo.

**Comment by qrkourier** [comment]
Reminder @dovholuknf wanted you to see this note before I merged it.

**Review by qrkourier — COMMENTED** [review]
Ready for your review @dovholuknf

**Comment by qrkourier** [comment]
> Ready for your review @dovholuknf

**Review by dovholuknf — APPROVED** [review]

**Pull request merged**
